name: Build_GSI  
  
on:  
 workflow_dispatch:   
    inputs:  
      ROM_URL:  
        description: 'ROM_URL'  
        required: true  
        default: 'https://jaist.dl.sourceforge.net/project/crdroid/clover/7.x/crDroidAndroid-11.0-20210113-clover-v7.2.zip'  
      ROM_NAME:  
        description: 'ROM_NAME'  
        required: true  
        default: 'crDroidAndroid-11.0-20210113-clover-v7.2.zip'  
      ROM_TYPE:  
        description: 'ROM_TYPE'  
        required: true  
        default: 'Generic'  
      BUILD_TYPE:  
        description: 'BUILD_TYPE'  
        required: true  
        default: 'ab'    
      TZ:  
        description: 'TZ'  
        required: true  
        default: 'Asia/Shanghai'  



jobs:
 Build_GSI:
    runs-on: ubuntu-20.04 
    
    steps:  
    - name: Check out this repository...  
      uses: actions/checkout@main  
  
    - name: Set up the environment...  
      run: |  
        sudo apt-get install -y git wget git zip unzip curl axel pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 python-is-python3 brotli  
  
    - name: Clone the ErfanGSI source code  
      run: git clone --recurse-submodules https://github.com/RAZTY/ErfanGSI.git ErfanGSI  
  
    - name: Fix Exit  
      run: |  
        sed -i 's/\|\| exit 1//g' ${{ github.workspace }}/ErfanGSI/url2GSI.sh  
        sed -i 's/exit 1//g' ${{ github.workspace }}/ErfanGSI/url2GSI.sh  
  
    - name: Set up requirements  
      run: |  
        cd ${{ github.workspace }}/ErfanGSI  
        mkdir ./output  
        sudo bash ./setup.sh  
  
    - name: Download Stock Rom & Generate GSI  
      run: |  
        cd ${{ github.workspace }}/ErfanGSI  
        sudo bash ./url2GSI.sh -c --${{ inputs.BUILD_TYPE }} ${{ github.event.inputs.ROM_URL }} ${{ inputs.ROM_NAME }}  
        
    - name: Packing GSI...      
      run: |      
        cd ${{ github.workspace }}/ErfanGSI/output    
        mkdir GHUT  
        tar -czvf ${{ github.workspace }}/ErfanGSI/output/GHUT/GSI.tar.gz ErfanGSI/output/
    
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
       files: |
         $GITHUB_WORKSPACE/ErfanGSI/output/GHUT/*
       tag_name: ${{ inputs.ROM_NAME }}
       body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      env: 
       GITHUB_TOKEN: ${{ secrets.GSI }}               
      
