name: Build_GSI  
  
on:  
 workflow_dispatch:   
    inputs:  
      ROM_URL:  
        description: 'ROM_URL'  
        required: true  
        default: 'http://bigota.d.miui.com/20.4.27/miui_MIMIX3_20.4.27_8f7879221b_10.0.zip'  
      ROM_NAME:  
        description: 'ROM_NAME'  
        required: true  
        default: 'miui_MIMIX3_20.4.27_8f7879221b_10.0.zip'  
      ROM_TYPE:  
        description: 'ROM_TYPE'  
        required: true  
        default: 'MIUI'  
      BUILD_TYPE:  
        description: 'BUILD_TYPE'  
        required: true  
        default: 'ab'    
      TZ:  
        description: 'TZ'  
        required: true  
        default: 'Asia/Shanghai'  



jobs:
 Build_GSI:
    runs-on: ubuntu-20.04 
    
    steps:  
    - name: Check out this repository...  
      uses: actions/checkout@main  
  
    - name: Set up the environment...  
      run: |  
        sudo apt-get install -y git wget git zip unzip curl axel aria2 pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 python-is-python3 brotli  
  
    - name: Clone the ErfanGSI source code  
      run: git clone --recurse-submodules https://github.com/RAZTY/ErfanGSI.git ErfanGSI  
  
    - name: Fix Exit  
      run: |  
        sed -i 's/\|\| exit 1//g' ${{ github.workspace }}/ErfanGSI/url2GSI.sh  
        sed -i 's/exit 1//g' ${{ github.workspace }}/ErfanGSI/url2GSI.sh  
  
    - name: Set up requirements  
      run: |  
        cd ${{ github.workspace }}/ErfanGSI  
        mkdir ./output  
        sudo bash ./setup.sh  
  
    - name: Download ROM Using aria2
      run: |
        cd ${{ github.workspace }}/ErfanGSI
        aria2c --user-agent="Mozilla/5.0" --dir="${{ github.workspace }}/ErfanGSI" --out="${{ inputs.ROM_NAME }}" "${{ github.event.inputs.ROM_URL }}" || echo "Download failed"
        if [[ -f "${{ github.workspace }}/ErfanGSI${{ github.event.inputs.ROM_NAME }}" ]]; then
        echo "Zip file downloaded successfully"
        else
        echo "Failed to download zip file"
        fi

    - name: Build GSI  
      run: |  
        cd ${{ github.workspace }}/ErfanGSI  
        bash ./url2GSI.sh -c --${{ inputs.BUILD_TYPE }} ${{ inputs.ROM_TYPE }}  
        
    - name: Packing GSI...  
      run: |  
        cd ${{ github.workspace }}/ErfanGSI/output  
        mkdir GSI  
        tar -czvf ${{ inputs.BUILD_TYPE }}_${{ inputs.ROM_NAME }}.tar.gz ${{ inputs.ROM_NAME }}  
        mv ${{ inputs.BUILD_TYPE }}_${{ inputs.ROM_NAME }}.tar.gz GSI/
          
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
       files: |
         $GITHUB_WORKSPACE/ErfanGSI/output/GSI/*
       tag_name: ${{ inputs.ROM_NAME }}
       body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      env: 
       GITHUB_TOKEN: ${{ secrets.GSI }}               
      
